### ISSUE TITLE
Feature request: ability to add breakpoints in run-time code generated by aspects

### ISSUE THREAD

**Issue by WhitWaldo** [postsharp/Metalama#133]
I have been working on adding unit tests to validate that the aspects applied to types and methods are working as expected by mocking injected dependencies and validating that they're capturing what they should. 

However, as I add new functionality, I frequently run into build errors that are reported by the error bar in Visual Studio. This is fine - I can usually figure out what's going wrong, but it gets more cumbersome when the aspect builds correctly but the output in the preview doesn't match what I'd like it to.

I'd like to ask for some sort of debugging step-through experience in which I can step through the code as it's applied at compile time so I can more richly understand how Metalama is doing what it's doing, identify richer opportunities for unit testing and more quickly troubleshoot and resolve bugs myself without resorting to a support ticket. 

Ideally, this would be little different than setting a breakpoint in a normal .NET application - I'd set a breakpoint in the aspect and when the project next rebuilt behind the scenes, the breakpoint would be hit for one of the applications of the aspect and I'd have the opportunity to step through and investigate the value of each compile-time variable. 

Thank you for the consideration!

**Comment by gfraiteur** [comment]
Whit,

It seems that you feature request is partly covered by the `LamaDebug` configuration as explained in https://doc.metalama.net/conceptual/using/debugging-aspect-oriented-code. The main gap I see is that breakpoints must be set in transformed code and not in the aspect code.

It would be very complex and perhaps impossible to allow you to set run-time breakpoints in aspect code using the UI because one line of aspect code maps to multiple lines of code in transformed code.

Could you please elaborate on what your request differs from the `LamaDebug` feature?

**Comment by WhitWaldo** [comment]
I'll dig into the documentation you linked and see if it's sufficient for what I had in mind and get back to you.

**Comment by WhitWaldo** [comment]
So, here's the problem I'm currently looking at. I'm looking at building out the behavior of a Blazor component based on the attributes applied to the type:

```cs
public abstract record EditStartAction();

public sealed class CanEdit<TEditAction> : Attribute
  where TEditAction : EditStartAction, new()
{
}

public record MyCreateStartAction : CreateStartAction
{
}

[GenerateBehavior]
[CanEdit<MyCreateStartAction>]
public partial class TestTable : FluxorComponent
{
}

public sealed class GenerateBehavior : TypeAspect
{
  public override void BuildAspect(IAspectBuilder<INamedType> builder)
  {
    var supportsEditing = builder.Target.Attributes.OfAttributeType(typeof(CanEditAttribute<>)).Any();

    if (supportsEditing) 
    {
      //Introduce a method
    }
  }
}
```

When the aspect builds, I don't see the method show up in the preview even though the attribute is applied. I'd really like to put a breakpoint on the line on which I'm assigning the value to `supportsEditing` so I can work to understand why it's not spotting that attribute on the type (and if it's picking up anything at all.

**Comment by gfraiteur** [comment]
Ok, I have renamed the ticket to what I think better describes what you wish.

This is very complex and I'm not even sure there is a good solution for this.

What you may do is to add a call to `Debugger.Break` in your aspect call. This would actually define an unconditional breakpoint and you would have to recompile to remove it.

Another approach may be to have a debugging helper class like this:

```cs
static class DebuggingHelper
{
   public static void ConditionalBreak( string aspectName, string targetTypeName, string targetMemberName )
  {
    // Put a conditional breakpoint with your UI here as needed.
   }
}
```

And you would inject a call to this helper using the aspect:

```cs
DebuggingHelper.ConditionalBreak( "TheAspect", meta.Target.Type.Name, meta.Target.Member.Name );
```

Then, using the UI of your IDE, you could set/unset breakpoints as needed and set a condition on the different parameters of the aspect.

Would that cover your needs?

**Comment by WhitWaldo** [comment]
Take another one I just did - checking to see what the names are of the fields or properties on the type:

```cs
//Aspect
public override void BuildAspect(IAspectBuilder<INamedType> builder)
{
  builder.Advice.IntroduceMethod(builder.Target, nameof(DebugMethod), IntroductionScope.Instance, OverrideStrategy.Ignore, 
    b => {b.Accessibility = Accessibility.Private; }, args: new {
        collection = builder.Target.AllFieldsAndProperties
    });
}

//...

    [Template]
    private void DebugMethod(IFieldOrPropertyCollection collection)
    {
        foreach (var item in collection)
        {
            Console.WriteLine(item.Name);
        }
    }
```

Produces this - very helpful for my purposes to know that I'm on the right track:
![image](https://github.com/postsharp/Metalama/assets/2238529/f9d2307b-c0a0-46f3-be5d-d1e60ceecf1d)
