### ISSUE TITLE
Typo in LAMA0041 exception text

### ISSUE THREAD

**Issue by WhitWaldo** [postsharp/Metalama#152]
LAMA0041: 'XYX' threw 'InvalidOperationException' when applied to 'MyModel': TemplateExpansionContext.CurrentSyntaxGenerationContext has not be set."

"be" should be "been"

**Comment by gfraiteur** [comment]
Thank you for reporting.

**Comment by prochan2** [comment]
Fixed in Metalama 2023.3.6-rc and 2023.4.2-preview.
