### ISSUE TITLE
Critical incompatibility (conditional RuntimeIdentifier); project fails to build after installing `Metalama.Framework`

### ISSUE THREAD

**Issue by Cheatoid** [postsharp/Metalama#16]
## Steps to reproduce
1. Download the [MetalamaIncompatibility.zip](https://github.com/postsharp/Metalama/files/8764947/MetalamaIncompatibility.zip) (example C# project).
2. Run `dotnet build` using cmd/terminal, or Build using your IDE/editor.

## Expected behavior
The project should build successfully (with `Metalama.Framework` package).

## Actual behavior
The project fails to build, simply because the `Metalama.Framework` package is installed.

**Comment by prochan2** [comment]
Thank you for reporting this issue, @Cheatoid . We have managed to reproduce it and we'll update this thread as soon as it's fixed.

**Comment by Cheatoid** [comment]
From what I can tell, this has been fixed in `0.5.22-preview`.
