### ISSUE TITLE
Typo in LAMA0510

### ISSUE THREAD

**Issue by curt-w** [postsharp/Metalama#18]
I believe parameters have been mixed up during string formatting; in the below exception that I am encountering, I believe "Class1" and "IEntityChangeTracking" should be swapped.

In the below example, Class1 is the concrete object and IEntityChangeTracking is the interface being implemented. Cheers and great work on this!

LAMA0510: The aspect 'ChangeTrackingTypesAspect' cannot implicitly introduce interface 'Class1' into the type 'IEntityChangeTracking' because it does not contain a declarative introduction (using [InterfaceMember]) for the interface member 'IEntityChangeTracking.IsFieldChanged(IEntityField)'.

**Comment by gfraiteur** [comment]
Solved in 0.5.31-preview.
