### ISSUE TITLE
Unhandled exception - using "nameof()" in specific situations

### ISSUE THREAD

**Issue by curt-w** [postsharp/Metalama#21]
Another low priority one, definitely not a blocker. Yesterday I had encountered issue utilizing "nameof()" in a specific implementation; I didn't think much of it until recent when I realized it is working successfully in other locations. I've found in most cases the operator works as expected, but I've been able to reproduce in one of the example projects you provide.

Based on the cloneable example, I've added "var test = nameof(Program);" to the aspect method [here](https://try.metalama.net/#N4IghiBcIPQwBAFQBYEsDO8PzAO3gPYAOAprgLToECuATgMYnwCyJALmADZgC2Y8JAB68inEgDp4AZRJNkbNkXSQ4Ac1Rtk1AEbj6BHjCIF0bdMjC0iMVh259xUkWMwAzArXg8PEgDq5-anRUXFUWdi5eMHEAMVpeEgB3DwBrcQBBdFJ6MwBuQODQ8Lso2PieJNTxAGECABMSfIDcXASssEZiyIcnHlESdBrOAlwSf2B-eCn4AG0ASVxkEloNEjqAXUnpmYAZVAA3EkQSPu42Ek38aZDz2lbOeHpudEwAEVkiauHR9IUV7Wo53gkCQAE9SJlsmwtlMJldptMiDpOKh6IRDrQVg14PsCKg6vAAELUVCcOqQkg5AAU8DmFJyxNJDVoAB45gA5BJ1RDgkgAPngAKZy3gAEoYQj4HDJTKcZZ4GxeXVbMh6vAALyCklk5YZOr7VESBZsWj1aiMFX1KkS2WSoU62jiRCWVTsAA0Ntt01aFQIripmgwQxGJDmp1FHvhXoRiSWuAAooIMGYQQB5DFYkhSE1gc6qUHidPLTOR6Myl3KeCjRJSpAarXCx3O2iutjwAC+YqanplitIyvYqrq4k5FXrvhAXxDE6aZYVSstw4ASuw6LgeaR6-bmU6Xexu1Hbdvdel9YbxGH+hVcGxjctXB0SNbD2Xj0292xS3Ppn2SH6qXMU6jGA2hiBGPZerGZCJsmlZFpi+JZjmeYFnMqi4D4XYQe2-gQTMxynLmT60ugABqqC0Gw1BcPWJrUEwoqXLaSKgaidZAaGpwsjMtR9KSRyoBU6xIHyVLii+sIQQicBIGgmD6HxYjkGwglMPslioCBYjwIkpIPLQlIkAcTCaEwQhEAZLyoCM8AGRZAxkCpRSmYKYDoEw9BcJw4hSdMMlzK4OlyGAhw4PALEomiHFeIO9RukFOl6fAQRMBo8ABnJWCYC59AWCEIRhEQua3LgoqSKmpm0Lp7lftGMmJEwumcA8nnNeEPDaMs1UkNFGXYNgLn5SpXCoAAXrm1n4H6CpLOFxXLKVPkSZKcyJvZVk2dobk9V5B5zupnjnKY9Y+n+-oAAqmqo5SirOZa+VMqCBTSFQcLuLbsOIi4Xug8GZmKD1SoDCKvdE7yuCEJBrZZwQjC9ETiIS23BqMYnxTQbZbe51ReVhy0Ijh+PTCQnDuYD0rflMoPiODkPQwMsO4PDb1I+5X0nJ1VUYD13xPhGhCAq52O47dgOE4DMm06MYXDK1corFpTDTS56AJPOm5uTNJkfurfhE1MB2PLz9ZUogopCztzXiKRXD0QAhHtZYyTIYg5EbIyK-AEMk3UgyA4bTwe6BJAxKgPuYOqwPTNTzatk6vKxGHZLoOkuB1JdxDLCpAziAA6ksBnPpTMqBeqAquD96SAgQGekJRoKprQoc+-AABkrdR2WVJUhXG5GugNK-v+gG84r5vm+3Xvx6QjjZJpnB9-AdualIc9cH3jgmgV5sAD4753Xe97yWW0qOayL97ZJn9yx+T5fdTXxv9JmCy7wkJ8vO-FvALnKJZWp6CMSopx6O2jO4AyHRkDpXll7JOBIQju1aMHZuycAb6yBug6SCBqhLHoCkLAgUGrwAsKFfgEU2KvSHPAAA5BxMS1CvYeC1rrQggUXL3yWsXGB99F6agAo-Xk5sOF9zupTAOvNFz1h4QnRcgxUyuETB0NgUhUDoVzHQYiE4OITniukTEYACzxj6IqNkfc-54wPk9aBgdRiSOwMAeA6R6CMCstoUkGhQQgicS44IbiUSKnEOdZEbFOx7wPpKaRM9n7oFfh8DiX9-iAn5GJDIuBAHjwPhTLhUx-KBVBAMeKrUHguUoWqXSmgMZhU8qYTh2SpgcIWLiFIyxBisxIHbRw7AbacHokXOpkobEkFqv0qmCMcamBpJEoZsCfYXlwE0lpiNkYAHEum22IjHTKooAD8KM+ZijxlwwmXCSZk0wdMLJ2TclVgIPFFKzCbj3kfLUupDT5kEGabQVp20OkyDYN03p4TZSDOGSM6m4y2CTLgX3eK3cR4hkVtsoRcC5kLK+Ustmqz-nrOZtEFA2BgG7LoePQ5xdjllnFuggyVE7iIMaNhXCy15g3ieRaDmywaRzHQGtSKaVNR0QYkxWUFkDhEUINoAAVpSNsxKNQCk2UGYloiOz+HbCAN0IAiBQFgAgfFmBsB4EIKQCgVA6CdFsN0fgQhnASGkLIYhCglAqBgOoTQOg9AGCMCYMwFgrA2AiPYaIvR+huCYd4AyS1GUAGILJgFUHwHSlhcAFXgHUDAntqhSAABwADYACMWb4AyXZCMcguBqDNU9vfLwQQ2z6BvGABB-AMIUHLW1dSPTGpxgEEmJyYR62mFoOaNgHhJC1FwMEZkqbKTcBWEUTWbbuDB0jS0NoRVzUBtKMGlwezxgShmG-D+IYhWPRZXcGiRVKLzyNm5TAVcR18BUkU0EHFFYSkuQichaIbiONAZKL9LA8DUWai+0ewciR-s-cEtE96DATWfa+8D1RIOImg-AEtbBEPaVeMqylCJHnnpas8TAzAgNeVAwi8DIJ4XAWDu+iCAGf3xhQ1MADBBJXSvgMSiCH7ZTUrXFWJIgHy3kaw-shx8ZaJyXEJJ9syqCYSjw9cM99wb0vHQwQTDYGxD0eWoxm88AYi4cZfhlTNEni3vgO8FYhwCReOro+1EontNjCjLx1jaHSMiZA2J+AyzaytlyOFGzYr3JsCC+SqYSnT0lXM8R+AGdrq8F08xELQJTDwZxHiAkpGQhiR4-7eUHhVEhBopqasjiHPwec5R7SDj0j1jzfFQkJ0hNeeA5wCjtG6vwEk5qAATB2eK1RWs1ms8ZAk9X6wAGYhtWdGxprTtWmAOJiPWAALB2DsLHJSXRuDSYr6h7jxQnId0rnAJwWPQeIkM9Yzv3D2WJHbCI9s3hpCC+Al2piDMu6LZoc4MtPqy-iBLc7IWVYfdVnzLnCDxUHSm06aC5zua9OOqgYg84rHOHsVG8AAAkE5gCnU7JqYA9X1TAAIBkdszWaYU6p4SGTNOuMZHpzUan8VXixDZ1zmInZ2w4RAKS6MkXJSi8Jmq9sQA).

While this is not the exact situation I was dealing with, I hope it depicts the issue I was encountering.

**Comment by prochan2** [comment]
Thank you for reporting this. I see that the method introduction doesn't work without any error being emitted in this case. The same happens even when I just declare a local run-time variable.

However, I only managed to reproduce this in Try Metalama, but not in a project that uses Metalama. Not event in the sample project from GitHub. Have you managed to reproduce it in a project? If you have, could you please share it with us?

**Comment by prochan2** [comment]
Thank you, @curt-w . I've created a new issue for the nameof, as your initial report has revealed a different bug In Metalama.Try.

**Comment by gfraiteur** [comment]
Solved in 0.5.31-preview.
