### ISSUE TITLE
When I use attribute injection in the attribute class, it prompts that the namespace of ILogger cannot be found

### ISSUE THREAD

**Issue by changhengyu** [postsharp/Metalama#24]
![image](https://user-images.githubusercontent.com/29672730/178641276-54e466b3-ff51-4ef6-abc4-d3d25664c748.png)
```cs
 public class LogAttribute : OverrideMethodAspect
    {
        public ILogger<LogAttribute> _logger{ get; set; }
        public override dynamic? OverrideMethod()
        {
            Console.WriteLine($"Entering {meta.Target.Method}");
            Console.WriteLine($"Entering {meta.Target.Parameters[0].Value}");

            try
            {
                return meta.Proceed();
            }
            finally
            {
                Console.WriteLine($"Leaving {meta.Target.Method}");
            }
        }
    }
```

**Comment by gfraiteur** [comment]
That's a confusing error message but the cause is that Metalama does not know what to do with the `_logger` property. I guess you need to annotate it with `[Introduce]`.

**Comment by changhengyu** [comment]
> That's a confusing error message but the cause is that Metalama does not know what to do with the `_logger` property. I guess you need to annotate it with `[Introduce]`.

Thanks very much ,the question had been resolved.
