### ISSUE TITLE
Code coverage is broken after MetaLama update

### ISSUE THREAD

**Issue by martonx** [postsharp/Metalama#28]
Hi All,

We found a strange issue. We use code coverage cheking on our tests. It worked with MetaLama 0.5.23-preview.
BUT after MetaLama update even just to 0.5.24-preview our code coverage shows only 0% on our code.

This is our test command:
`dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:Threshold=80 /p:Include="[*]MySolution.Core.*"`

We use Coverlet for code coverage generation.
Nuget packages:
coverlet.collector version 3.1.2
coverlet.msbuild version 3.1.2

Could you check what happend between Metalama 0.5.23-preview and 0.5.24-preview? Please fix code coverage issue somehow!

Thank you very much!

**Comment by gfraiteur** [comment]
Thank you for reporting this issue.
Honestly, I am surprise that code coverage even worked in the past. We don't have any test coverage for test coverage at the moment. I will look into that.

**Comment by martonx** [comment]
Thank you very much!

**Comment by gfraiteur** [comment]
This is fixed in 0.5.33. 
There is still work to make code coverage work perfectly when there are non-inlineable aspects on your code, but at least it should not break.
