### ISSUE TITLE
Validation: Throw error if first argument in target method invocation doesn't use `nameof()`

### ISSUE THREAD

**Issue by WhitWaldo** [postsharp/Metalama#315]
I've got a collection of ideas that I'd like to write Metalama aspects for, but I'm struggling to figure out how to start. I'm looking to eventually contribute this work to an open source project, but as it'll probably be a larger discussion of taking on the Metalama dependency, I'm starting by implementing it on my own.

The project in question is the [Dapr workflow](https://docs.dapr.io/developing-applications/building-blocks/workflow/workflow-overview/) and specifically as it's used in their [.NET client](https://github.com/dapr/dotnet-sdk). Without getting into a bunch of details, this is an implementation of the [Durable Task](https://github.com/Azure/durabletask) framework and it's written to be language agnostic, so it invokes things via named references, one inputs `objects` and it outputs JSON values deserialized to the values you specify. All well and good in theory, but in practice, this means that there's a lot of room to mess things up (e.g. refactor an activity name and suddenly the workflow identifying the activity via a string doesn't work anymore), among other issues.

I've got a collection of things I'd like to address using Metalama (as it's simply easier to use and more flexible than the Roslyn code analysis tooling) to ideally throw a warning or an error during the build process based on the inspection, but I'm stumped about how to proceed. Here is the first one I'm trying to tackle (believe it or not, the easiest, I think):

*Goal:* Validate that whenever an activity is started, it passes the activity name via `nameof()` instead of a string value.
An activity is typically invoked by something like the following within a type implementing a `Workflow<InputType, OutputType>`:
```cs
public override async Task<OutputType> RunAsync(WorkflowContext context, InputType input)
{
  await context.CallActivityAsync<bool>(nameof(MyActivity1), input.property);
}
```
Here, I imagine I'd use a fabric to apply the aspect to every class that implements `Workflow<,>` and has a `RunAsync` method. But where each of the Metalama examples either creates the implementation around the target method in some way or another, I don't see anything quite analogous to what I'm trying to do, namely: 
1) Identify the name of the first argument (of type `WorkflowContext` on the `RunAsync` method itself
2) Identify each line within the method that starts with `await <contextVariableName>.CallActivityAsync`
3) Retrieve the first argument of the CallActivityAsync method invocation and validate that it is implemented as a `nameof()`.
4) If so, all is good, proceed without warning. If any call to CallActivityAsync doesn't use `nameof()` on the first argument, create and throw a build warning.

Is this possible? Thanks!

**Comment by svick** [comment]
In general, Metalama does not give you access to method bodies, which means it's not very suitable for this kind of analysis.

I think the best you can do with Metalama is to use Metalama.Framework.Sdk to get access to the Roslyn types for the relevant code, e.g.:

```c#
class ValidateRunAsyncAttribute : TypeAspect
{
    public override void BuildAspect(IAspectBuilder<INamedType> builder)
    {
        var compilation = builder.Target.Compilation.GetRoslynCompilation();

        var runAsyncMethod = builder.Target.Methods.OfName("RunAsync").SingleOrDefault();

        var runAsyncSyntax = (MethodDeclarationSyntax)runAsyncMethod.Sources.Single().NodeOrToken;

        // You can inspect the method syntax here, or get its IOperation.
    }
}
```

But at this point, Metalama does not give you much that you couldn't do with a plain Roslyn analyzer.
