### ISSUE TITLE
Incorrect "Metalama paused...." notification 

### ISSUE THREAD

**Issue by XtroTheArctic** [postsharp/Metalama#331]
Metalama+PostSharp Extension version: 2024.1.24

I'm seeing this notification while my project has no errors and it builds perfectly.

Repo: ssh://git@bitbucket.org/XtroTheArctic/unitycommons-commons.git
Branch: feature/MetalamaUpdate

Gael and Daniel has access to the repo.

![image](https://github.com/user-attachments/assets/38a8b704-15bd-4c51-98d3-787ccc0281d3)

**Comment by addabis** [comment]
Hello. The hidden error is:

```
Cannot find in the current compilation the aspect type 'Atesh.Metalama.NotNullOrWhiteSpaceAttribute' defined in the aspect library 'Atesh'.
```

It is related to the problem with PrivateAssets="all", i.e. Metalama does not see the compile-time assembly for "Atesh" package and is not able to find the aspect.

The fact that you do not get the error in the normal build is strange and we will be treating the lack of error details as a bug.

**Comment by XtroTheArctic** [comment]
Hello again.

I got the prior screenshot of this error notification after I got rid of the use of PrivateAssets="all".

Now I checked it again, I'm still getting the error notification. It should not be caused by PrivateAssets="all".

This change was on the branch "feature/MetalamaUpdate" if you checking my repo.

![image](https://github.com/user-attachments/assets/d9c493d3-f173-463b-9a57-890c33e1b7a5)

**Comment by addabis** [comment]
I have used your branch and the error disappeared after I removed PrivateAssets="all" for the `Atesh` and `Atesh.Metalama` package references in the solution (the error itself occurred in one of the test projects).

Can you point me to a branch/commit where you are sure this did not happen?

Thanks.

**Comment by XtroTheArctic** [comment]
On MetalamaUpdate branch, privateassets is already removed and I get the
notification as soon as I start VS. Are you sure you got the latest of that
branch?

I’ll record a video for you in the morning (PST)

**Comment by XtroTheArctic** [comment]
Oh oh. I am sorry. Now I noticed there were more PrivateAssets="all" usages in other projects in the solution. I thought you were mentioning the ones in Atesh.Unity (root project in the solution). Sorry for all the confusion. It's good now.

**Comment by addabis** [comment]
No problem. The error is due to the same mechanism, but the fact that normal build passes and design-time build does not is a bit strange.

I have filed a bug to improve the error message.
