### ISSUE TITLE
Introduced constructors not recognized by IDEs

### ISSUE THREAD

**Issue by CaffeinatedCoder** [postsharp/Metalama#332]
I am fiddling around with new features that are coming with Metalama 2024.2.

In my own tests I could observe that introducing new constructors is indeed working, the sole problem is that introduced constructors aren't recognized at all by Intellisense in Visual Studio nor by code analysis in JetBrains Rider. I can prove that the constructor has been indeed added to the type, I can even compile projects using these newly introduced constructors without errors, but IDEs aren't aware of these at all while writing code using these constructors.
This is completely different to e.g. introduced methods, fields or properties, these are being recognized right away.

**Comment by addabis** [comment]
Hello,

the design-time support is implemented so this would indicate that there is something broken.

I can confirm it is easy to replicate the issue. We will be working on a fix.

Thanks.

**Comment by gfraiteur** [comment]
Fixed in  2024.2.17-rc.
