### ISSUE TITLE
Feature: Specify 'this' keyword on introduced parameters

### ISSUE THREAD

**Issue by WhitWaldo** [postsharp/Metalama#339]
I would like to introduce a static extension method to a type and am able to create the method and mark it as static without issue. But when introducing the parameters to the introduced method, there isn't an option to indicate that the 'this' keyword should be inserted, leaving one unable to actually create an extension method.

```cs
        var serviceCollectionType = (INamedType)TypeFactory.GetType(typeof(IServiceCollection));
        
        builderType.IntroduceMethod(nameof(BuildMethodTemplate),
            IntroductionScope.Static,
            buildMethod: b =>
            {
                b.Name = "RegisterAllEntities";
                b.Accessibility = Accessibility.Public;
                //b.AddParameter("serviceCollection", serviceCollectionType); //Need some way to specify 'this'
            });
```

I would like to request such a capability. Thank you for the consideration!

**Comment by gfraiteur** [comment]
Thank you for spotting this gap.

**Comment by prochan2** [comment]
This feature has been added in Metalama 2025.0.5-preview.
