### ISSUE TITLE
Upgrade from 2024.1.22 to 2024.2.18 introduces new LAMA0233/LAMA0001 build errors 

### ISSUE THREAD

**Issue by HowardFedTec** [postsharp/Metalama#347]
First, thank you for taking the time to review my issue and assist with resolving it if possible.

I am attempting to upgrade our Metalama packages from v2024.1.22 to v2024.2.18.
![image](https://github.com/user-attachments/assets/1f5f3e49-4d9d-453b-99be-66f6527722f1)

I am unable to update the metalama command line tool. I will create a separate ticket for that.

The NuGet update is successful.
The compilation now fails for code that previously worked.

I am experiencing 31 errors now. This is the first two that are related. The others are CSC errors that may or may not clear themselves after resolving these two errors.

### **Code:**
The problem lines are commented with: //<<<< COMPILATION ERROR
```
private static InterpolatedStringBuilder BuildInterpolatedString(bool includeOutParameters, bool IncludeParameters=true, bool IncludeParameterNames = true, bool IncludeParameterValues = true)
{
    var stringBuilder = new InterpolatedStringBuilder();

    // Include the type and method name.
       stringBuilder.AddText(meta.Target.Type.ToDisplayString(CodeDisplayFormat.MinimallyQualified));
        stringBuilder.AddText(".");
        stringBuilder.AddText(meta.Target.Method.Name);
        stringBuilder.AddText("(");
        var i = meta.CompileTime(0);  //<<<< COMPILATION ERROR
        if (IncludeParameters)
        {
            // Include a placeholder for each parameter.
            foreach (var p in meta.Target.Parameters)
            {
                var comma = i > 0 ? ", " : "";

                if (p.RefKind == RefKind.Out && !includeOutParameters)
                {
                    if (IncludeParameterNames)
                    {
                        // When the parameter is 'out', we cannot read the value.
                        stringBuilder.AddText($"{comma}{p.Name} = <out> ");
                    }
                }
                else
                {
                    if (IncludeParameterNames)
                    {
                        // Otherwise, add the parameter value.
                        stringBuilder.AddText($"{comma}{p.Name} = {{");
                    }
                    if (IncludeParameterValues)
                    {
                        stringBuilder.AddExpression(p.Value); //<<<< COMPILATION ERROR
                    }
                    stringBuilder.AddText("}");
                }

                i++;
            }
        }
        stringBuilder.AddText(")");
        return stringBuilder;
}
```

### **Errors:**
The first error I do not understand as I am still new to using Metalama. I understand the message about it not being a template, but the method has never been a template in the past.

The second error explanation makes sense. It appears to be fixed by using "p" instead of "p.value". Not sure if that works as intended because I cannot overcome the first error.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/HOWARD~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/HOWARD~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Severity | Code | Description
-- | -- | --
Error   (active) | LAMA0233 | Cannot use   'meta.CompileTime<int>(int)' in   'LogAttribute.BuildInterpolatedString(bool, bool, bool, bool)' because it is   only allowed inside a template.
Error   (active) | LAMA0233 | Cannot use   'IExpression.Value' in 'LogAttribute.BuildInterpolatedString(bool, bool,   bool, bool)' because it is only allowed inside a template. Use 'p' directly   instead of accessing 'p.Value'.
</body>
</html>

**Comment by gfraiteur** [comment]
Indeed, this is by design. We noticed some people were using some APIs incorrectly so we added validations and errors.

* `meta.CompileTime(0)` is redundant. Just replace it by `0`.
* Instead of `AddExpression(p.Value)`, do `AddExpression(p)`.
