### ISSUE TITLE
work-around for MetaLama Attribute: how to get output in Visual Studio 2022

### ISSUE THREAD

**Issue by billwoo** [postsharp/Metalama#8]
Hope this saves you some time.

Users of VS 2022 have probably gotten used to using Debug,xxx instead of Console,.xxx methods.

Internal writes inside a Metalama Attribute will only appear (for me) if:

1, Tools/Options/Debugging/General: enable redirect all output window text  to Immediate Window

2, in the Attribute: use Debug.xxx not Console.xxx

Why this is required: if I tried to think about this, my headache will get worse :)

**Comment by gfraiteur** [comment]
Thanks for the tip bill!.
